pipeline {
    agent {
        docker {
            image 'node:18.15.0'
            args '-p 3000:3000'
        }
    }
    stages {
        stage('Test') {
            steps {
                sh 'npm test'
            }
        }
    }
}